### ISSUE TITLE
Error when padding PIL image in mode P

### ISSUE THREAD

**Issue by npmhung** [pytorch/pytorch.github.io#811]
To regenerate the issue:

F.pad(Image.fromarray(np.zeros((300,300))).convert('P'), (3,3))

Error messages:

Traceback (most recent call last):
  File "/home/npmhung/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/npmhung/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 454, in pad
    return F_pil.pad(img, padding=padding, fill=fill, padding_mode=padding_mode)
  File "/home/npmhung/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchvision/transforms/functional_pil.py", line 153, in pad
    image = ImageOps.expand(img, border=padding, **opts)
  File "/home/npmhung/miniconda3/envs/pytorch/lib/python3.7/site-packages/PIL/ImageOps.py", line 403, in expand
    draw.rectangle((0, 0, width - 1, height - 1), outline=color, width=border)
  File "/home/npmhung/miniconda3/envs/pytorch/lib/python3.7/site-packages/PIL/ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: an integer is required (got type tuple)

**Comment by TrackingBird** [comment]
Hi Sir，sorry to borther，had you solved this problem？I got the same result.
